version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "icecream-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cviv4jmtws5g"
s3_prefix = "icecream-service"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
